apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: helloworld-subscription
  namespace: helloworld-app
spec:
  channel: helloworld-chn/helloworld-channel
  packageOverrides:
    - packageName: <package_name>
      packageAlias: <package_alias>
  placement:
    placementRef:
      kind: Placement
      name: helloworld-placement
