---
name: Pull request

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: darwin-x64
          - os: ubuntu-latest
            target: linux-x64
          - os: windows-latest
            target: win32-x64
      fail-fast: false
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Install project modules
        run: npm i

      - name: Cache vscode-test folder
        uses: actions/cache@v3
        with:
          path: .vscode-test
          key: ${{ runner.os }}-vscode-test-${{ hashFiles('package.json') }}

      - name: Run unit tests
        run: npm test

      - name: Run integration tests linux
        if: runner.os == 'Linux'
        run: xvfb-run -a npm run integration-tests

      - name: Run integration tests non-linux
        if: runner.os != 'Linux'
        run: npm run integration-tests

      - name: Create a VSIX package for target ${{ matrix.target }}
        run: >
          npm run vsce:package --
          --target ${{ matrix.target }}
          --out ocm-vscode-extension-${{ matrix.target }}-dev.vsix
